<?php

declare(strict_types=1);

use Illuminate\Contracts\Routing\UrlGenerator;
use Illuminate\Process\PendingProcess;
use Illuminate\Support\Facades\Process;
use Zacksmash\Outpost\ApplicationHttps;

beforeEach(function () {
    Process::preventStrayProcesses();

    $this->urls = Mockery::mock(UrlGenerator::class);
    $this->https = new ApplicationHttps($this->urls);
});

it('uses the scheme generated by the Laravel application', function () {
    $this->urls->shouldReceive('to')->once()->with('/')->andReturn('https://summit-test.test');
    Process::fake();

    expect($this->https->detected())->toBeTrue();

    Process::assertNothingRan();
});

it('detects a trusted https listener when the configured app url still uses http', function () {
    $this->urls->shouldReceive('to')->once()->with('/')->andReturn('http://summit-test.test');
    Process::fake([
        '*' => Process::result('HTTP/2 502'),
    ]);

    expect($this->https->detected())->toBeTrue();

    Process::assertRan(fn (PendingProcess $process) => $process->command === [
        'curl',
        '--head',
        '--silent',
        '--show-error',
        '--output', '/dev/null',
        '--connect-timeout', '1',
        '--max-time', '2',
        'https://summit-test.test',
    ]);
});

it('uses http when the same host has no trusted https listener', function () {
    $this->urls->shouldReceive('to')->once()->with('/')->andReturn('http://summit-test.test');
    Process::fake([
        '*' => Process::result('', 'connection refused', 7),
    ]);

    expect($this->https->detected())->toBeFalse();
});

it('does not probe unsupported application url schemes', function () {
    $this->urls->shouldReceive('to')->once()->with('/')->andReturn('mailto:developer@example.com');
    Process::fake();

    expect($this->https->detected())->toBeFalse();

    Process::assertNothingRan();
});

it('caches the detected scheme for the command lifecycle', function () {
    $this->urls->shouldReceive('to')->once()->with('/')->andReturn('http://summit-test.test');
    Process::fake([
        '*' => Process::result('HTTP/2 200'),
    ]);

    expect($this->https->detected())->toBeTrue()
        ->and($this->https->detected())->toBeTrue();

    Process::assertRanTimes(fn (PendingProcess $process) => ($process->command[0] ?? null) === 'curl', 1);
});
